// Partially auto-generated by zbus-xmlgen
use zbus::proxy;
#[proxy(
	interface = "org.freedesktop.systemd1.Unit",
	default_service = "org.freedesktop.systemd1"
)]
pub trait SystemdUnit {
	#[zbus(property)]
	fn active_state(&self) -> zbus::Result<String>;

	#[zbus(property)]
	fn sub_state(&self) -> zbus::Result<String>;

	#[zbus(property)]
	fn state_change_timestamp(&self) -> zbus::Result<u64>;
}
